"""Update fact list with latest from Rayid

Revision ID: 3e57dbd296d0
Revises: 402477247aef
Create Date: 2014-05-06 11:55:08.165502

"""

# revision identifiers, used by Alembic.
revision = '3e57dbd296d0'
down_revision = '402477247aef'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friend_fbid_facts_hourly', sa.Column('distinct_faces_shown', sa.Integer(), nullable=True))
    op.add_column('misc_facts_hourly', sa.Column('clicks', sa.Integer(), nullable=True))
    op.add_column('misc_facts_hourly', sa.Column('total_faces_shown', sa.Integer(), nullable=True))
    op.add_column('misc_facts_hourly', sa.Column('total_shares', sa.Integer(), nullable=True))
    op.add_column('visit_facts_hourly', sa.Column('visits_facepage_rendered', sa.Integer(), nullable=True))
    op.add_column('visit_facts_hourly', sa.Column('visits_generated_faces', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visit_facts_hourly', 'visits_generated_faces')
    op.drop_column('visit_facts_hourly', 'visits_facepage_rendered')
    op.drop_column('misc_facts_hourly', 'total_shares')
    op.drop_column('misc_facts_hourly', 'total_faces_shown')
    op.drop_column('misc_facts_hourly', 'clicks')
    op.drop_column('friend_fbid_facts_hourly', 'distinct_faces_shown')
    ### end Alembic commands ###
