"""Add visits with share clicks

Revision ID: 402477247aef
Revises: 44aafda313ae
Create Date: 2014-05-02 14:04:18.250119

"""

# revision identifiers, used by Alembic.
revision = '402477247aef'
down_revision = '44aafda313ae'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visit_facts_hourly', sa.Column('visits_with_share_clicks', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visit_facts_hourly', 'visits_with_share_clicks')
    ### end Alembic commands ###
