"""Hourly aggregate tables

Revision ID: 43f31a2c0730
Revises: None
Create Date: 2014-04-02 07:41:09.542407

"""

# revision identifiers, used by Alembic.
revision = '43f31a2c0730'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dimensions',
    sa.Column('dimension_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('pretty_name', sa.String(), nullable=True),
    sa.Column('column', sa.String(), nullable=True),
    sa.Column('source_table', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('dimension_id')
    )
    op.create_table('misc_facts_hourly',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('hour', sa.DateTime(), nullable=False),
    sa.Column('visitors', sa.Integer(), nullable=True),
    sa.Column('no_friends', sa.Integer(), nullable=True),
    sa.Column('declined_auth', sa.Integer(), nullable=True),
    sa.Column('authorizations', sa.Integer(), nullable=True),
    sa.Column('shares_failed', sa.Integer(), nullable=True),
    sa.Column('clickbacks', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('campaign_id', 'hour')
    )
    op.create_table('visitors',
    sa.Column('visitor_id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('fbid', sa.BigInteger(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('visitor_id')
    )
    op.create_table('events',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('client_content', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('friend_fbid', sa.BigInteger(), nullable=True),
    sa.Column('activity_id', sa.BigInteger(), nullable=True),
    sa.Column('event_datetime', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('facts',
    sa.Column('fact_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('pretty_name', sa.String(), nullable=True),
    sa.Column('expression', sa.String(), nullable=True),
    sa.Column('dimension_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('fact_id')
    )
    op.create_table('friend_fbid_facts_hourly',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('hour', sa.DateTime(), nullable=False),
    sa.Column('friend_fbid', sa.BigInteger(), nullable=False),
    sa.Column('friends_shared_with', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('campaign_id', 'hour', 'friend_fbid')
    )
    op.create_table('ip_facts_hourly',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('hour', sa.DateTime(), nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('ip_session_start', sa.Integer(), nullable=True),
    sa.Column('ip_cookies', sa.Integer(), nullable=True),
    sa.Column('ip_visitors', sa.Integer(), nullable=True),
    sa.Column('ips_declined_auth', sa.Integer(), nullable=True),
    sa.Column('ips_authorized', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('campaign_id', 'hour', 'ip')
    )
    op.create_table('visits',
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('visitor_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('appid', sa.BigInteger(), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('referer', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('visit_id')
    )
    op.create_table('fbid_facts_hourly',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('hour', sa.DateTime(), nullable=False),
    sa.Column('fbid', sa.BigInteger(), nullable=False),
    sa.Column('fbids_authorized', sa.Integer(), nullable=True),
    sa.Column('fbids_generated_friends', sa.Integer(), nullable=True),
    sa.Column('fbids_shown_friends', sa.Integer(), nullable=True),
    sa.Column('fbids_face_pages', sa.Integer(), nullable=True),
    sa.Column('fbids_shared', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('campaign_id', 'hour', 'fbid')
    )
    op.create_table('visit_facts_hourly',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('hour', sa.DateTime(), nullable=False),
    sa.Column('visit_id', sa.BigInteger(), nullable=False),
    sa.Column('visit_ids', sa.Integer(), nullable=True),
    sa.Column('visits_declined_auth', sa.Integer(), nullable=True),
    sa.Column('visits_shown_friend_sugg', sa.Integer(), nullable=True),
    sa.Column('authorized_visits', sa.Integer(), nullable=True),
    sa.Column('visits_with_shares', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('campaign_id', 'hour', 'visit_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visit_facts_hourly')
    op.drop_table('fbid_facts_hourly')
    op.drop_table('visits')
    op.drop_table('ip_facts_hourly')
    op.drop_table('friend_fbid_facts_hourly')
    op.drop_table('facts')
    op.drop_table('events')
    op.drop_table('visitors')
    op.drop_table('misc_facts_hourly')
    op.drop_table('dimensions')
    ### end Alembic commands ###
